name: conduit_api
description: API for financial accounting.
version: 1.0.0

environment:
  sdk: '>=2.18.7 <3.0.0'

dependencies:
  path: ^1.8.0
  jaguar_jwt: ^3.0.0
  conduit: ^4.3.9
  build_runner: ^2.1.4
  build: ^2.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
